### ISSUE TITLE
Contributing to the digital garden directory

### ISSUE THREAD

**Issue by mithi** [MaggieAppleton/digital-gardeners#36]
Hi, 

Thanks to this repository, I have been inspired to create my own digital garden.
I started customizing it to suit my personal taste (`mdx`, searchable by `tags`, minimalist design).
It doesn't have entries yet but I think it will be mostly about `robotics`, `math`, `coding`, `react`, `front-end development`.

https://github.com/mithi/digital-garden

I was wondering, if the `digital garden directory` is your own curated collection of hand picked digital garden or it is a list  where other people can also submit PRs to add other people's gardens? (Thinking of even adding my own... maybe when I have already shared and written some cool stuff in the near future)

Thanks again!

**Comment by MaggieAppleton** [comment]
Hi Mithi,

Apologies for the late response on this!
The repo is a hand-picked collection of gardens, although people do PR theirs in as contributions.
I tend to only accept gardens to the list when they're quite well-grown, and/or have a distinct style and structure to them.
While I certainly don't want to discourage any budding gardeners, there's an awful lot of brand new gardens on the web that don't have a whole lot of material on them.
As a rule of thumb, gardens with 40-50+ posts up and/or ones experimenting with creative garden formats feel more useful as examples to include in the list. Want to show a diversity of garden styles and content in this repo.
So yes, you're more than welcome to submit PR's with any gardens you think deserve to be included!

Hope that helps. Your garden looks like it's off to a great start and would love to include it once it's had some time to grow :)

**Comment by mithi** [comment]
Okay! Thanks for the reply @MaggieAppleton ! :D
