### ISSUE TITLE
Innos Note - A knowledge garden for curious mind. 

### ISSUE THREAD

**Issue by 6174** [MaggieAppleton/digital-gardeners#62]
Site:  [https://innos.io](https://innos.io?s=github)
Youtube Video: https://www.youtube.com/watch?v=0JvzUIHfktU
![image](https://user-images.githubusercontent.com/3872872/119308420-9a54c200-bc9f-11eb-926d-d92e3fc20916.png)

**Comment by MaggieAppleton** [comment]
Thanks for the suggestion, just added https://github.com/MaggieAppleton/digital-gardeners/commit/2361ff92d6592673468cbdfd3ea932a2f487da75
